AllCops:
  Exclude:
    - './**'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'


Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false