default: &default
  adapter: postgresql
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  username: <%= ENV['DB_USERNAME'] %>
  timeout: <%= ENV['DB_TIMEOUT'] %>
  encoding: <%= ENV['DB_ENCODING'] %>
  reconnect: <%= ENV['DB_RECONNECT'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DEV_DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] %>

production:
  <<: *default
  database: <%= ENV['PROD_DB_NAME'] %>
