name: RuboCop Lint # Имя рабочего процесса
on:
  push:

jobs:
  lint_check:
    runs-on: ubuntu-latest # Виртуальная машина

    steps:
      - name: Checkout code # 1. Получаем код
        uses: actions/checkout@v4

      - name: Set up Ruby # 2. Настраиваем окружение
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6' # Замените на вашу версию Ruby
          bundler-cache: true # Ускоряет установку Gem'ов, включая RuboCop

      - name: Run RuboCop only on changed files # 3. Основная логика
        id: rubocop_check
        run: |
          # 1. Определяем диапазон коммитов для сравнения
          NULL_HASH="0000000000000000000000000000000000000000"
          
          if [ "${GITHUB_EVENT_BEFORE}" == "$NULL_HASH" ] || [ -z "${GITHUB_EVENT_BEFORE}" ]; then
            # СЦЕНАРИЙ 1: Первый пуш в новую ветку или некорректный before. Сравниваем с HEAD~1.
            RANGE="HEAD~1..HEAD"
          else
            # СЦЕНАРИЙ 2: Обычный пуш в существующую ветку.
            RANGE="${GITHUB_EVENT_BEFORE}..HEAD"
          fi

          # 2. Получаем список измененных/добавленных (.rb) файлов
          CHANGED_FILES=$(git diff --name-only --diff-filter=AM $RANGE | grep '\.rb$')

          if [ -z "$CHANGED_FILES" ]; then
            echo "Нет измененных Ruby-файлов для проверки. Проверка пропущена."
            exit 0
          fi
          
          echo "Проверка RuboCop для следующих файлов в диапазоне $RANGE: $CHANGED_FILES"
          
          # 3. Запускаем RuboCop только для этих файлов
          bundle exec rubocop $CHANGED_FILES